# Generated by Django 3.1.7 on 2021-03-28 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudsederhana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_secondary_person', to='crudsederhana.person')),
                ('id_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_primary_person', to='crudsederhana.person')),
            ],
        ),
    ]
