# Generated by Django 3.1.7 on 2021-03-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudsederhana', '0002_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Laki-laki'), (1, 'Perempuan')]),
        ),
    ]
