# Generated by Django 3.1.7 on 2021-03-28 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudsederhana', '0003_auto_20210328_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='root',
            name='id_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_primary_person', to='crudsederhana.person', unique=True),
        ),
    ]
